Repository 4monument/sb1-monew-team04, pull requests merged in 2025-05, with the labels that each got.

#159 test: CommentRepositoryImpl 테스트 코드 추가
  src/main/java/com/sprint/monew/domain/comment/CommentService.java
  src/main/java/com/sprint/monew/domain/comment/repository/CommentRepository.java
  src/main/java/com/sprint/monew/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/sprint/monew/domain/comment/repository/CommentRepositoryImpl.java
  src/test/java/com/sprint/monew/domain/comment/CommentRepositoryTest.java
Labels: enhancement

#165 test: 테스트 코드 mongoTemplate Bean 불러올 수 없는 오류 수정
  src/test/java/com/sprint/monew/domain/activity/UserActivityQueryRepositoryTest.java
  src/test/java/com/sprint/monew/domain/comment/CommentRepositoryTest.java
  src/test/java/com/sprint/monew/domain/interest/InterestIntegrationTest.java
  src/test/java/com/sprint/monew/domain/interest/InterestRepositoryTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint/monew/domain/user/UserRepositoryTest.java
  src/test/java/com/sprint/monew/integration/UserIntegrationTest.java
Labels: bug

#167 test: 조회 테스트 수정 및 MongoDB 빈 문제 해결로 주석 처리 제거
  src/test/java/com/sprint/monew/domain/interest/InterestIntegrationTest.java
Labels: enhancement

#168 test: 테스트 데이터베이스 연결 풀 관리 개선 및 테스트 코드 구현
  src/main/java/com/sprint/monew/domain/notification/NotificationService.java
  src/test/java/com/sprint/monew/domain/interest/InterestIntegrationTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationServiceTest.java
  src/test/resources/application-test.yaml
  src/test/resources/seed-test.sql
Labels: enhancement

#180 docs: Swagger 작성, README.md에 codecov 및 Deploy 상태 뱃지 추가
  .github/README.md
  build.gradle
  src/main/java/com/sprint/monew/common/config/SwaggerConfig.java
  src/main/java/com/sprint/monew/common/config/api/ArticleApi.java
  src/main/java/com/sprint/monew/common/config/api/CommentApi.java
  src/main/java/com/sprint/monew/common/config/api/InterestApi.java
  src/main/java/com/sprint/monew/common/config/api/NotificationApi.java
  src/main/java/com/sprint/monew/common/config/api/UserActivityApi.java
  src/main/java/com/sprint/monew/common/config/api/UserApi.java
  src/main/java/com/sprint/monew/domain/activity/UserActivityController.java
  src/main/java/com/sprint/monew/domain/article/ArticleController.java
  src/main/java/com/sprint/monew/domain/comment/CommentController.java
  src/main/java/com/sprint/monew/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/sprint/monew/domain/interest/InterestController.java
  src/main/java/com/sprint/monew/domain/notification/NotificationController.java
  src/main/java/com/sprint/monew/domain/notification/NotificationService.java
  src/main/java/com/sprint/monew/domain/user/UserController.java
  src/main/resources/application.yaml
Labels: documentation

#183 feat: Article 조회 API 개발
  src/main/java/com/sprint/monew/domain/article/Article.java
  src/main/java/com/sprint/monew/domain/article/ArticleService.java
  src/main/java/com/sprint/monew/domain/article/dto/ArticleDto.java
  src/main/java/com/sprint/monew/domain/article/dto/request/ArticleRequest.java
  src/main/java/com/sprint/monew/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/sprint/monew/domain/article/repository/ArticleRepositoryImpl.java
  src/main/resources/schema.sql
  src/main/resources/seed.sql
  src/test/resources/db/migration/V1__init_schema.sql
  src/test/resources/schema-insert-article.sql
  src/test/resources/seed-test.sql
Labels: enhancement

#192 fix: 알림 테스트 코드 주석 제거 및 수정, 관심사 버그 수정
  src/main/java/com/sprint/monew/domain/interest/InterestService.java
  src/main/java/com/sprint/monew/domain/interest/dto/InterestCreateRequest.java
  src/main/java/com/sprint/monew/domain/interest/dto/InterestUpdateRequest.java
  src/main/java/com/sprint/monew/domain/notification/Notification.java
  src/main/java/com/sprint/monew/domain/notification/NotificationService.java
  src/test/java/com/sprint/monew/domain/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationServiceTest.java
Labels: bug, enhancement

#209 fix: 댓글 삭제시 댓글 개수가 줄어들지 않는 오류 수정
  src/main/java/com/sprint/monew/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/sprint/monew/domain/comment/like/Like.java
  src/main/resources/schema.sql
  src/test/resources/db/migration/V1__init_schema.sql
Labels: bug

#208 hotfix: 알림, 관심사 조회 파라미터 유효값 수정
  src/main/java/com/sprint/monew/common/config/api/InterestApi.java
  src/main/java/com/sprint/monew/common/config/api/NotificationApi.java
  src/main/java/com/sprint/monew/domain/interest/InterestController.java
  src/main/java/com/sprint/monew/domain/notification/NotificationController.java
  src/main/java/com/sprint/monew/domain/notification/NotificationService.java
  src/main/java/com/sprint/monew/domain/notification/dto/NotificationSearchRequest.java
  src/main/java/com/sprint/monew/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/sprint/monew/domain/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/resources/seed.sql
  src/test/java/com/sprint/monew/domain/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint/monew/domain/notification/NotificationServiceTest.java
Labels: bug

#218 hotfix: swagger-ui 에서 CORS 미설정으로 인한 요청 불가 오류 수정
  src/main/java/com/sprint/monew/common/config/WebConfig.java
Labels: bug
